# Generated by Django 3.1.2 on 2022-08-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20220816_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtp',
            name='orderCount',
            field=models.IntegerField(default=0),
        ),
    ]
